/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import EndMenu from "./scripts/EndMenu"
import Loading from "./scripts/Loading"
import SGHomeUI from "./SGSDK/SGHomeUI"
import SGScale from "./SGSDK/SGScale"
import SGRemen from "./SGSDK/SGRemen"
import Shop from "./scripts/Shop"
import SkinLock from "./scripts/SkinLock"
import Stage from "./scripts/Stage"
import StageUpdate from "./scripts/StageUpdate"
import StartMenu from "./scripts/StartMenu"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="Loading.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("scripts/EndMenu.ts",EndMenu);
        reg("scripts/Loading.ts",Loading);
        reg("SGSDK/SGHomeUI.ts",SGHomeUI);
        reg("SGSDK/SGScale.ts",SGScale);
        reg("SGSDK/SGRemen.ts",SGRemen);
        reg("scripts/Shop.ts",Shop);
        reg("scripts/SkinLock.ts",SkinLock);
        reg("scripts/Stage.ts",Stage);
        reg("scripts/StageUpdate.ts",StageUpdate);
        reg("scripts/StartMenu.ts",StartMenu);
    }
}
GameConfig.init();